#!/bin/sh

set -e

[ ! -d /var/lib/mac ] && mkdir /var/lib/mac

mac_file="/var/lib/mac/mac.$IFACE"

if [ ! -r "$mac_file" ]
then
    echo "Storing MAC for $IFACE for future use." > /dev/stderr
    cat /sys/class/net/usb0/address > "$mac_file"
    exit 0
fi

stored=`cat "$mac_file"`
current=`cat /sys/class/net/usb0/address`

if [ "$current" != "$stored" ]
then
    echo "Setting back to old MAC."
    ifconfig $IFACE hw ether $stored
fi
